### ISSUE TITLE
Extra Emission of <Handle>_window Event

### ISSUE THREAD

**Issue by justacec** [daattali/timevis#127] opened 2023-02-10 00:21 UTC
I have enabled the mouse dragging and zooming functionality in the `timeviz` widget.  I have found that the `input$<Handle>_window` event is fired *both* when I regenerate the widget and click-drag/zoom with the mouse in the window.  While I expect the event to be fired based on the mouse movements, I did not expect the event to fire when the widget is established.  

I took a look at the code in the inst/htmlwidgets/timevis.js file and found the following lines:

```
            // The range of the window has changes (by dragging or zooming)
            timeline.on('rangechanged', function (properties) {
              Shiny.onInputChange(
                elementId + "_window",
                [timeline.getWindow().start, timeline.getWindow().end]
              );
            });
            Shiny.onInputChange(
              elementId + "_window",
              [timeline.getWindow().start, timeline.getWindow().end]
            );

```

Based on these, it seems as though the _window event is fired when the widget is initialized.  It seems this is from the second call to Shiny.onInputChange().  

Is this the correct behavior?  Am I using the widget incorrectly?  I looked to see if there was a way to update the dataframe for the widget and did not see that discussed in the documentation.

I really just want to know when the user actually clicks and manually adjusts the widget.

I am using the following related software versions:
R: 4.2.1
shiny: 1.7.4
timevis: 2.1.0

**Comment by justacec** [comment] 2023-02-13 11:53
I have created a PR to cover this (mostly) at #128 for review.  

Might make sense to remove the second emission but I would wait for your feedback on that.

**Comment by daattali** [comment] 2023-04-02 07:31
Hi @justacec , thanks for opening this and taking initiative to fix something you think is broken.
First, I apologize for taking so long to respond, I try to dedicate different weeks to different packages and didn't get to timevis until now. 

The behaviour you're seeing is actually a feature, not a bug :) It is functioning as intended. Remember that  that `input$timevis_window` is an input. I think that will make it easier to understand why it works this way. It's not meant to be an event in timevis, because shiny doesn't really work by the concept of "events", shiny works with the concept of inputs. If you initialize a textInput, you will have access to its value immediately when the app starts via `input$text`. If you create a `DT::DTOutput()` table , then you immediately have access to a range of input values that are generated in javascript the moment the table initializes, such as `input$table_rows_current` and many others.

If this was not the case, then `input$timevis_window` would be NULL until the user manually moves it, which is not correct. It's meant to give you the current value of the window, at any time.

I hope you can see the reasoning. Let me know if you have any more questions.

**Comment by daattali** [comment] 2023-04-13 05:39
I'm closing this issue and its associated PR. Feel free to re-open if you think I'm wrong

**Closed by daattali** 2023-04-13 05:39 UTC
