### ISSUE TITLE
'verticalScroll' option can not work on my end

### ISSUE THREAD

**Issue by LuqiKong** [daattali/timevis#43] opened 2018-01-15 20:09 UTC
I want to add a vertical bar to the Gantt Chart so that I can scroll vertically. There is a '**verticalScroll**' option in **Timeline** library in Javascript, but it can not work when I tried this option in R Timevis. Since the Timevis library in R is binding to the Timeline library in JS, I expect the options in JS should also work in R. Not sure if there is any problem on my end. Really appreciate it if you can contribute your ideas!

Here is a sample code I tried but failed to get the 'vertical scroll' feature:

`library(shiny)
library(timevis)

data <- data.frame(
  id      = 1:4,
  content = c("Item one", "Item two",
              "Ranged item", "Item four"),
  start   = c("2016-01-10", "2016-01-11",
              "2016-01-20", "2016-02-14 15:00:00"),
  end     = c(NA, NA, "2016-02-04", NA)
)

ui <- fluidPage(
  timevisOutput("timeline")
)

server <- function(input, output, session) {
  output$timeline <- renderTimevis({
    timevis(data, options = list(verticalScroll = TRUE , orientation = 'top'))
  })
}

shinyApp(ui = ui, server = server)`

Thanks,
Luqi

**Comment by daattali** [comment] 2018-01-15 21:15
If the option is supposed to be that simple to use (simply `verticalScroll = TRUE`) and it's not working, my best initial guess is that the feature is not supported on the visjs Timeline version that is used in this package. Did you see when that feature got added? timevis uses visjs version 4.16

**Comment by daattali** [comment] 2018-01-15 21:18
It looks like the verticalScroll feature was indeed introduced after 4.16 according to this thread https://github.com/almende/vis/issues/1186

That means it will not work in timevis until https://github.com/daattali/timevis/issues/32 is solved

**Comment by daattali** [comment] 2018-01-15 21:18
I'm closing this issue because it's essentially a duplicate of #32 and will be solved when that one is solved

**Closed by daattali** 2018-01-15 21:18 UTC

**Comment by LuqiKong** [comment] 2018-01-15 21:32
Thank you, Dean! Look forward to the new release.

**Comment by daattali** [comment] 2018-01-15 21:38
As mentioned in the other thread, I've tried a few times upgrading to a
newer version but it never went smoothly. So I'm hoping someone else can
dedicate a few hours to help with it because I'm involved in too many other
projects at the moment

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>
