### ISSUE TITLE
How to remove/make invisible the horizontal gridlines between the groups?

### ISSUE THREAD

**Issue by yelekley** [daattali/timevis#152] opened 2024-10-01 15:30 UTC
Hello,
How to remove/make invisible the horizontal gridlines between the groups?
Thanks

**Comment by daattali** [comment] 2024-10-05 05:34
You can look at the documentation of the javascript library to see if there is a builtin way to do that, but I doubt it https://visjs.github.io/vis-timeline/docs/timeline/

Otherwise, you'll have to write some simple custom CSS to remove those lines.

This is a CSS issue, not a bug/feature of timevis, so I'm closing the issue

**Closed as completed by daattali** 2024-10-05 05:34 UTC
