### ISSUE TITLE
Issues with zooming when vis 4.20 is loaded (with visNetwork for example)

### ISSUE THREAD

**Issue by DanielAbdelNour** [daattali/timevis#36] opened 2017-08-11 01:46 UTC
The latest visNetwork updates use vis 4.20 which overrides timevis' vis 4.16. As a result, the zoom functionality breaks when zoomed to show months. 

Here's a reproducible example (note the version numbers).

ps. Love your work, Dean :)

```
library(shiny)
library(timevis) #0.4.0.9000
library(visNetwork) #2.0.2

server <- function(input, output) {
   output$timevis <- renderTimevis({
      timevis()
   })

   output$visnet <- renderVisNetwork({
      visNetwork()
   })
}

ui <- fluidPage(
   useShinyjs(),
   sidebarLayout(
      sidebarPanel(),
      mainPanel(
         timevisOutput("timevis"),
         visNetworkOutput("visnet")
      )
   )
)

shinyApp(ui = ui, server = server)
```

**Comment by daattali** [comment] 2017-08-11 14:46
Thanks for the report @DanielAbdelNour 
The initial title for this issue mentions a CSS class - did you actually track this down this issue to being caused by a css class? An update is due for timevis, but unfortunately every time I have 20 minutes to spare and I look into updating, I find some bugs caused by the update so I revert.

If anyone has some time and is able to help with updating to the latest timevis (and ensuring that all functionality still works), it would be a very welcomed pull request!

**Comment by daattali** [comment] 2017-08-11 14:47
related  to #32

**Comment by daattali** [comment] 2018-03-02 01:41
related to #50

**Comment by daattali** [comment] 2020-09-11 01:50
This would be fixed once I can upgrade to the latest version

**Closed by daattali** 2020-09-11 01:50 UTC
