### ISSUE TITLE
Timevis excluding data

### ISSUE THREAD

**Issue by jshibley** [daattali/timevis#126] opened 2022-10-28 18:10 UTC
Hello,

I'm using the timevis package in R Shiny to create a timeline of interactions with 5,000 different physicians. On the dashboard I built, there is a filter built in, and the user can select a physician (dropdown) and then it shows all the interactions in a timeline form. I'm finding that it is only showing only a subset of physicians in the dropdown filter (up to ones with "S" in the last name). Is there a way to include all the physicians so none get dropped? Don't know if this is a memory issue, or additional code I need to include related to the timevis package. Thanks.

**Comment by daattali** [comment] 2022-10-28 19:48
It's not possible to know what the issue here is without seeing a reproducible example. It could be a timevis issue that I've never seen before but it could be a shiny issue or could just be something the code is doing wrong. Please provide a [minimal reprex](https://community.rstudio.com/t/faq-how-to-do-a-minimal-reproducible-example-reprex-for-beginners/23061)

**Comment by jshibley** [comment] 2022-10-28 20:12
Thanks for the quick response. I'll pull together an example and will share.

**Comment by daattali** [comment] 2022-10-28 20:21
Thanks, just make sure it's a minimal example that isolates the issue

**Comment by daattali** [comment] 2023-04-02 07:09
Closing due to no example

**Closed by daattali** 2023-04-02 07:09 UTC
