### ISSUE TITLE
Stack order within groups based on date?

### ISSUE THREAD

**Issue by jernest1** [daattali/timevis#114] opened 2021-04-23 08:03 UTC
When using groups where the items have longer labels, they are stacked vertically so they don't overlap. Depending on the zoom level, the items may be stacked in order of date or may not be. Is there a way to force the vertical stacking to be in order of date? For instance, I would like "really long name one" to be on the top.
```
myData = data.frame(start = c("2021-01-01", "2021-01-08", "2021-02-15", 
                              "2021-04-23"),
                    content = c("really long name one", "really long name two", 
                                "really long name three", "really long name four"),
                    group = c("Group A", "Group A", "Group A", "Group B"))
myGroups = data.frame(id = c("Group A", "Group B"),
                      content = c("Group A", "Group B"))
timevis(data = myData, groups = myGroups)

```
![image](https://user-images.githubusercontent.com/13725669/115839414-a15e8b00-a3e8-11eb-84e7-4d228768a288.png)

**Comment by daattali** [comment] 2021-04-23 08:13
I don't know if that's supported. Please see the documentation for the u deploying javascript library https://visjs.github.io/vis-timeline/docs/timeline/ to see if this feature is supported

**Comment by jernest1** [comment] 2021-04-23 08:25
There is orientation, orientation.axis, and orientation.item in Configuration Options. I'm using timevis in a Shiny app, and for some reason setting `options(orientation = "top")` does what I want for stacking, but it also puts the axis on the top. So maybe orientation.item is what I need. How would I use orientation.item in R? Setting `options(orientation.item = "top")` had no effect.

**Comment by daattali** [comment] 2021-04-23 16:09
It wouldn't be orientation.item, the documentation for `orientation` means that it's a list, and `item` is an element in that list. My best bet would be to try `orientation = list(item="top")`. This may or may not work, if it doesn't you'll have to drop into javascript, figure out how it looks like in javascript exactly, and then mimic that in R, knowing that R converts the options to json

**Comment by jernest1** [comment] 2021-04-23 16:52
Thanks. Setting `orientation = list(item = "top")` did stack the items by date, but it draws the vertical lines running to the top instead of the axis at the bottom. `orientation = list(item = "top", axis = "bottom")` had the same effect. I can live with the axis being at the top if there's no way to force the vertical lines to run downward.

**Comment by daattali** [comment] 2021-09-13 22:22
This is caused by the underlying visjs library, not by timevis. Closing this issue

**Closed by daattali** 2021-09-13 22:22 UTC
